
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.services.streamclient.webrtc-1.3.8.zip"
    repository = "https://gitlab-master.nvidia.com/omniverse/kit-extensions/kit-livestream.git"

    [package.publish]
        kitVersion = "105.0.2+release.109455.818d8fa0.tc"
        date = 1691082818
        buildNumber = "105.0+105.0.955.df87df41.tc"
        repoName = "kit-livestream"
        signed = 1

    [package.authors]
        0 = "Philippe Sawicki <psawicki@nvidia.com>"
        1 = "Jozef van Eenbergen <jeenbergen@nvidia.com>"
