
[package]
    archivePath = "https://d4i3qtqj3r0z5.cloudfront.net/omni.kit.markup.core-1.2.20.zip"

    [package.publish]
        kitVersion = "105.2+release.137156.76c0b151.tc"
        date = 1723196980
        buildNumber = "105.1+master.1535.50bcd035.gl"
        repoName = "kit-windows"
        signed = 1
